// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzIGedK7wNuf6JXx5D1K6c1UvFM635JNU',
    appId: '1:103212730336:web:036bbfb8af4f43aa650d85',
    messagingSenderId: '103212730336',
    projectId: 'currency-project-496dd',
    authDomain: 'currency-project-496dd.firebaseapp.com',
    storageBucket: 'currency-project-496dd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQG-Guc5inxZpTmOGh6Ag4bVaahSLsXVQ',
    appId: '1:103212730336:android:bdf690519bdc7d4c650d85',
    messagingSenderId: '103212730336',
    projectId: 'currency-project-496dd',
    storageBucket: 'currency-project-496dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2_k6GK81tkhCPkdxvofxFLl24d4xvko8',
    appId: '1:103212730336:ios:9ac6fca51e7ec0dd650d85',
    messagingSenderId: '103212730336',
    projectId: 'currency-project-496dd',
    storageBucket: 'currency-project-496dd.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
